### PR TITLE
toan left us (#33)

### PR DESCRIPTION
**Pull request by ktokto313**
I had just finished high school when the emptiness hit me. I felt that working extensively had degraded my strength, both mentally and physically, so I decided to take the usual university route to find what I was really missing. I am grateful for everything I have experienced and learned from this team. I am sorry for not being able to follow everyone to the end of the journey. Thank you for everything!

### CODE REVIEW

**Review by 0x5ea000000 — APPROVED** [review]
Whatever path you choose, I wish you good luck and hope to see you again in the future.

**Comment by bjergsen243** [comment]
Good luck bro!

**Review by bjergsen243 — APPROVED** [review]

**Comment by Draply** [comment]
Hope to see you again in the future. GLHF!

**Comment by hduoc2003** [comment]
LGTM

**Review by hduoc2003 — APPROVED** [review]

**Review by Tranduy1dol — APPROVED** [review]
Good luck!

**Review by zk-steve — APPROVED** [review]

**Pull request merged**
